packages:
  - "packages/*"
  - "packages/plugins/*"
  - "examples/*"
allowBuilds:
  canvas: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@aether-labs/vitepress-mermaid@0.1.1'
  - '@aether-labs/vitepress-mermaid@0.1.2'
